In [4]:
import torch

import torch.nn as nn

import torch.nn.functional as F

In [5]:
x=torch.Tensor(3,3)

In [6]:
x


tensor([[1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39],
        [9.2755e-39, 9.1837e-39, 9.3674e-39]])

In [7]:
y=torch.rand(3,3)

In [8]:
y

tensor([[0.5578, 0.5365, 0.3175],
        [0.4212, 0.6654, 0.7358],
        [0.5120, 0.2630, 0.3736]])

In [9]:
x=torch.Tensor(3,3)*5
x[:,0:2]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net,self).__init__()
        self.conv1=nn.Conv2d(1,64,kernel_size=(3,3),padding=1)
        self.conv2=nn.Conv2d(64,64,kernel_size=(3,3),padding=1)
        self.max_pool=nn.MaxPool2d(2,2)
        
        self.global_pool=nn.AvgPool2d(7)
        
        self.fc1=nn.Linear(64,64)
        self.fc2=nn.Linear(64,10)
        
    def forward(self,x):
        x=F.relu(self.conv1(x))
        
        x=F.relu(self.conv2(x))

        x=self.max_pool(x)
        
        
        x=F.relu(self.conv2(x))
        
        x=F.relu(self.conv2(x))
        
        x=self.max_pool(x)
        
        
        x=F.relu(self.conv2(x))
        
        x=F.relu(self.conv2(x))
        
        x=self.global_pool(x)
        
        x=x.view(-1,64)
        
        x=F.relu(self.fc1(x))
        
        x=self.fc2(x)
        
        x=f.log_softmax(x)
        
        
        return x

        
        
        
        