In [6]:
import torch
import numpy as np 

In [3]:
a=torch.tensor([7,4,3,2,1])

In [4]:
a[0]

tensor(7)

In [6]:
a[0]


tensor(7)

In [7]:
a.dtype()

TypeError: 'torch.dtype' object is not callable

In [8]:
a.dtype

torch.int64

In [9]:
a.type()

'torch.LongTensor'

In [10]:
a=torch.tensor([0.0,1.0,2.0,3.0,4.0,5.0],dtype=torch.int32)

In [11]:
a.dtype

torch.int32

In [12]:
a[2]

tensor(2, dtype=torch.int32)

In [13]:
a=torch.FloatTensor([0,1,2,3])

In [14]:
a.type

<function Tensor.type>

In [16]:
numpy_array=np.array([1,2,3,4,5])
torch_tensor=torch.from_numpy(numpy_array)
back_to_numpy=torch_tensor.numpy()

In [19]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [20]:
A=torch.tensor(a)

A.ndimension()

In [21]:
A.ndimension()

2

In [22]:
A.size()

torch.Size([3, 3])

In [23]:
A.numel


<function Tensor.numel>

In [24]:
A.numel()

9

In [25]:
A[0][2]

tensor(3)

In [26]:
A[0,0:2]

tensor([1, 2])

In [28]:
Y=torch.tensor([[2,1],[1,2]])

In [29]:
Z=2*Y

In [30]:
Z

tensor([[4, 2],
        [2, 4]])

In [31]:
A.Z

AttributeError: 'Tensor' object has no attribute 'Z'

In [33]:
A*Z

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [34]:
A*Y

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [39]:
A=torch.tensor([[1,2],[2,3]])
B=torch.tensor([[2,1],[1,2]])


In [40]:
Z=A*B

In [41]:
Z

tensor([[2, 2],
        [2, 6]])

In [43]:
C=torch.mm(A,B)

In [44]:
C

tensor([[4, 5],
        [7, 8]])

In [49]:
x=torch.tensor(2.0,requires_grad=True)
y=x**2
y.backward()
x.grad


tensor(4.)

In [50]:
x=torch.tensor(2.0,requires_grad=True)
z=x**2+2*x+1
z.backward()
x.grad

tensor(6.)

In [52]:
u=torch.tensor(1.0,requires_grad=True)
v=torch.tensor(2.0,requires_grad=True)

f=u*v+u**2
f.backward()
u.grad


tensor(4.)

In [7]:
from torch.utils.data import Dataset

In [8]:
class toy_set(Dataset):
    def __init__(self,length=100,transform=None):
        self.x=2*torch.ones(length,2)
        self.y=torch.ones(length,1)
        self.len=length
        self.transform=transform 
    def __getitem__(self,index):
        sample=self.x[index],self.y[index]
        if self.transform:
                sample=self.transform(sample)
        return sample
    def __len__(self):
        return self.len 

In [9]:
dataset=toy_set()

for i in range(3):
    x,y=dataset[i]
    print('x:',x,'y:',y)
    

x: tensor([2., 2.]) y: tensor([1.])
x: tensor([2., 2.]) y: tensor([1.])
x: tensor([2., 2.]) y: tensor([1.])


In [10]:
class add_mult(object):
    
    def __init__(self,addx=1,muly=1):
        self.addx=addx
        self.muly=muly
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        sample=x,y
        return sample  
    

In [12]:
a_m=add_mult()
x_,y_=a_m(dataset[0])

In [13]:
x_

tensor([3., 3.])

In [14]:
y_

tensor([1.])

In [15]:
dataset_=toy_set(transform=a_m)

In [16]:
dataset_[0]

(tensor([3., 3.]), tensor([1.]))

In [17]:
class mult(object):
    def __init__(self,mul=1000):
        self.mul=mul
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x*self.mul
        y=y*self.mul
        sample=x,y
        return sample 

In [18]:
from torchvision import transforms

In [19]:
data_transform=transforms.Compose([add_mult(),mult()])

In [20]:
x_,y_=data_transform(dataset[0])

In [21]:
x_

tensor([3000., 3000.])

In [22]:
y_


tensor([1000.])

In [30]:
from PIL import Image
import pandas as pd 
import os
from matplotlib.pyplot import imshow
from torch.utils.data import Dataset,DataLoader

In [31]:
directory="E:\Study material\Pytorch\fashionmnist"
csv_file='fashion-mnist_train.csv'
csv_path=os.path.join(directory,csv_file)

In [32]:
data_name=pd.read_csv(csv_path)
data_name.head()

FileNotFoundError: File b'E:\\Study material\\Pytorch\x0cashionmnist\\fashion-mnist_train.csv' does not exist

In [60]:
from keras.datasets import fashion_mnist
((trainX, trainY), (testX, testY)) = fashion_mnist.load_data()

C:\Users\USER\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


ImportError: Could not import tensorflow. Do not import tensorflow from its source directory; change directory to outside the TensorFlow source tree, and relaunch your Python interpreter from there.

In [61]:
from PIL import Image
import pandas as pd 
import os
from matplotlib.pyplot import imshow
from torch.utils.data import Dataset,DataLoader

In [62]:
directory="D:\Tour\fashion-mnist.tar\fashion-mnist"
csv_file='fashion-mnist_train.csv'
csv_path=os.path.join(directory,csv_file)

In [63]:
data_name=pd.read_csv(csv_path)
data_name.head()

FileNotFoundError: File b'D:\\Tour\x0cashion-mnist.tar\x0cashion-mnist\\fashion-mnist_train.csv' does not exist

In [58]:
print('FileName:',data_name.iloc[1,1])

FileName: 0


In [59]:
print('Class or y',data_name.iloc[1,0])

Class or y 0
