In [1]:
import torch
import numpy as np

inputs=np.array([[73,67,43],
               [91,88,64],
               [87,134,58],
               [102,43,37],
               [69,96,70]],dtype='float32')

In [2]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [3]:
#convert numpy array to tensors

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [4]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [5]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [6]:
#weights and biases 

w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
w
b


tensor([-0.7573, -1.4154], requires_grad=True)

In [7]:
w

tensor([[-0.9622, -1.2770, -1.0146],
        [ 0.8352,  0.4804,  1.2710]], requires_grad=True)

In [8]:
b

tensor([-0.7573, -1.4154], requires_grad=True)

In [9]:
def model(x):
    return x @ w.t() + b



In [10]:
#predictions

preds=model(inputs)
print(preds)


tensor([[-200.1888,  146.3913],
        [-265.6328,  198.2036],
        [-314.4403,  209.3359],
        [-191.3572,  151.4550],
        [-260.7673,  191.2995]], grad_fn=<AddBackward0>)


In [11]:
def mse(t1,t2):
    diff=t1-t2
    return torch.mean((diff**2))

In [13]:
loss=mse(preds,targets)

In [14]:
print(loss)

tensor(59094.3945, grad_fn=<MeanBackward0>)


In [15]:
#compute gradients

loss.backward()

In [16]:
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [17]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [18]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(216.1115, grad_fn=<MeanBackward0>)


In [19]:
#Linear Regression Using pytorch built in

import torch.nn as nn

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [23]:
from torch.utils.data import TensorDataset

In [24]:
#Define Dataset
train_ds=TensorDataset(inputs,targets)


In [25]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [26]:
from torch.utils.data import DataLoader

In [27]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [28]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 22.,  37.]])


In [29]:
for xb,yb in train_dl:
    print(xb)
    print(yb)

tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[ 81., 101.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 22.,  37.]])
tensor([[ 73.,  67.,  43.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.]])
tensor([[ 56.,  70.],
        [ 56.,  70.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.]])
tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [119., 133.],
        [ 81., 101.]])


In [30]:
#Define model
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[ 0.1781, -0.2776,  0.1820],
        [ 0.1126,  0.2353,  0.4949]], requires_grad=True)
Parameter containing:
tensor([ 0.4985, -0.3365], requires_grad=True)


In [31]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1781, -0.2776,  0.1820],
         [ 0.1126,  0.2353,  0.4949]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4985, -0.3365], requires_grad=True)]

In [33]:
preds=model(inputs)
preds

tensor([[  2.7262,  44.9276],
        [  3.9245,  62.2886],
        [-10.6493,  69.6928],
        [ 13.4607,  39.5748],
        [ -1.1219,  64.6644],
        [  2.7262,  44.9276],
        [  3.9245,  62.2886],
        [-10.6493,  69.6928],
        [ 13.4607,  39.5748],
        [ -1.1219,  64.6644],
        [  2.7262,  44.9276],
        [  3.9245,  62.2886],
        [-10.6493,  69.6928],
        [ 13.4607,  39.5748],
        [ -1.1219,  64.6644]], grad_fn=<AddmmBackward>)

In [34]:
#importing nn.Functional
import torch.nn.functional as F


In [35]:
loss_fn=F.mse_loss

In [36]:
loss=loss_fn(model(inputs),targets)

In [37]:
#Define Optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5) #Note that model.parameters() is passed as an argument to optim.SGD, so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate which controls the amount by which the parameters are modified.

In [38]:
#Utility function to train the model 

In [44]:
def fit(num_epochs,model,loss_fn,opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            
            pred=model(xb)
            
            loss=loss_fn(pred,yb)
            
            loss.backward()
            
            opt.step()
            
            
            
            opt.zero_grad()
            
             # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            
            

In [47]:
fit(10000, model, loss_fn, opt)

Epoch [10/10000], Loss: 0.7990
Epoch [20/10000], Loss: 0.9876
Epoch [30/10000], Loss: 0.4639
Epoch [40/10000], Loss: 0.7274
Epoch [50/10000], Loss: 0.7176
Epoch [60/10000], Loss: 0.7270
Epoch [70/10000], Loss: 0.8529
Epoch [80/10000], Loss: 0.4334
Epoch [90/10000], Loss: 1.0042
Epoch [100/10000], Loss: 0.9836
Epoch [110/10000], Loss: 0.8082
Epoch [120/10000], Loss: 0.8062
Epoch [130/10000], Loss: 0.5981
Epoch [140/10000], Loss: 0.7731
Epoch [150/10000], Loss: 0.6554
Epoch [160/10000], Loss: 0.6540
Epoch [170/10000], Loss: 0.6085
Epoch [180/10000], Loss: 0.4206
Epoch [190/10000], Loss: 0.7621
Epoch [200/10000], Loss: 0.4654
Epoch [210/10000], Loss: 0.6062
Epoch [220/10000], Loss: 0.6887
Epoch [230/10000], Loss: 0.3465
Epoch [240/10000], Loss: 0.7346
Epoch [250/10000], Loss: 0.4812
Epoch [260/10000], Loss: 0.4026
Epoch [270/10000], Loss: 0.6216
Epoch [280/10000], Loss: 0.6056
Epoch [290/10000], Loss: 0.5037
Epoch [300/10000], Loss: 0.7464
Epoch [310/10000], Loss: 0.3726
Epoch [320/10000]

Epoch [2520/10000], Loss: 0.5945
Epoch [2530/10000], Loss: 0.6224
Epoch [2540/10000], Loss: 0.5760
Epoch [2550/10000], Loss: 0.3651
Epoch [2560/10000], Loss: 0.4555
Epoch [2570/10000], Loss: 0.6049
Epoch [2580/10000], Loss: 0.3736
Epoch [2590/10000], Loss: 0.5958
Epoch [2600/10000], Loss: 0.6244
Epoch [2610/10000], Loss: 0.7951
Epoch [2620/10000], Loss: 0.4774
Epoch [2630/10000], Loss: 0.7508
Epoch [2640/10000], Loss: 0.5388
Epoch [2650/10000], Loss: 0.5907
Epoch [2660/10000], Loss: 0.6666
Epoch [2670/10000], Loss: 0.5162
Epoch [2680/10000], Loss: 0.4650
Epoch [2690/10000], Loss: 0.4039
Epoch [2700/10000], Loss: 0.3669
Epoch [2710/10000], Loss: 0.5872
Epoch [2720/10000], Loss: 0.5027
Epoch [2730/10000], Loss: 0.4928
Epoch [2740/10000], Loss: 0.6696
Epoch [2750/10000], Loss: 0.5950
Epoch [2760/10000], Loss: 0.6355
Epoch [2770/10000], Loss: 0.4330
Epoch [2780/10000], Loss: 0.5163
Epoch [2790/10000], Loss: 0.7913
Epoch [2800/10000], Loss: 0.4909
Epoch [2810/10000], Loss: 0.6891
Epoch [282

Epoch [5000/10000], Loss: 0.5162
Epoch [5010/10000], Loss: 0.5482
Epoch [5020/10000], Loss: 0.7025
Epoch [5030/10000], Loss: 0.6197
Epoch [5040/10000], Loss: 0.5932
Epoch [5050/10000], Loss: 0.3772
Epoch [5060/10000], Loss: 0.4039
Epoch [5070/10000], Loss: 0.4431
Epoch [5080/10000], Loss: 0.5223
Epoch [5090/10000], Loss: 0.4270
Epoch [5100/10000], Loss: 0.6541
Epoch [5110/10000], Loss: 0.4274
Epoch [5120/10000], Loss: 0.6129
Epoch [5130/10000], Loss: 0.5162
Epoch [5140/10000], Loss: 0.5279
Epoch [5150/10000], Loss: 0.5977
Epoch [5160/10000], Loss: 0.6137
Epoch [5170/10000], Loss: 0.6925
Epoch [5180/10000], Loss: 0.6050
Epoch [5190/10000], Loss: 0.7901
Epoch [5200/10000], Loss: 0.6218
Epoch [5210/10000], Loss: 0.5684
Epoch [5220/10000], Loss: 0.4429
Epoch [5230/10000], Loss: 0.5166
Epoch [5240/10000], Loss: 0.4894
Epoch [5250/10000], Loss: 0.4566
Epoch [5260/10000], Loss: 0.5162
Epoch [5270/10000], Loss: 0.5463
Epoch [5280/10000], Loss: 0.6489
Epoch [5290/10000], Loss: 0.5529
Epoch [530

Epoch [7480/10000], Loss: 0.6650
Epoch [7490/10000], Loss: 0.6255
Epoch [7500/10000], Loss: 0.5353
Epoch [7510/10000], Loss: 0.6677
Epoch [7520/10000], Loss: 0.5162
Epoch [7530/10000], Loss: 0.5479
Epoch [7540/10000], Loss: 0.6544
Epoch [7550/10000], Loss: 0.4416
Epoch [7560/10000], Loss: 0.4408
Epoch [7570/10000], Loss: 0.4888
Epoch [7580/10000], Loss: 0.3250
Epoch [7590/10000], Loss: 0.4184
Epoch [7600/10000], Loss: 0.5162
Epoch [7610/10000], Loss: 0.5914
Epoch [7620/10000], Loss: 0.5946
Epoch [7630/10000], Loss: 0.4981
Epoch [7640/10000], Loss: 0.5640
Epoch [7650/10000], Loss: 0.4892
Epoch [7660/10000], Loss: 0.6137
Epoch [7670/10000], Loss: 0.5007
Epoch [7680/10000], Loss: 0.3696
Epoch [7690/10000], Loss: 0.8097
Epoch [7700/10000], Loss: 0.5163
Epoch [7710/10000], Loss: 0.6155
Epoch [7720/10000], Loss: 0.5274
Epoch [7730/10000], Loss: 0.4723
Epoch [7740/10000], Loss: 0.6147
Epoch [7750/10000], Loss: 0.7324
Epoch [7760/10000], Loss: 0.6713
Epoch [7770/10000], Loss: 0.5884
Epoch [778

Epoch [9960/10000], Loss: 0.6278
Epoch [9970/10000], Loss: 0.5162
Epoch [9980/10000], Loss: 0.4026
Epoch [9990/10000], Loss: 0.9462
Epoch [10000/10000], Loss: 0.5932


In [48]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.2215,  70.2559],
        [ 82.1209, 100.7117],
        [118.6412, 132.9734],
        [ 21.0449,  37.0273],
        [101.9004, 119.1337],
        [ 57.2215,  70.2559],
        [ 82.1209, 100.7117],
        [118.6412, 132.9734],
        [ 21.0449,  37.0273],
        [101.9004, 119.1337],
        [ 57.2215,  70.2559],
        [ 82.1209, 100.7117],
        [118.6412, 132.9734],
        [ 21.0449,  37.0273],
        [101.9004, 119.1337]], grad_fn=<AddmmBackward>)

In [49]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])